#==============================================================
# Debug mode
#==============================================================
localhost: http://localhost:3000
# debug : true
debug : false


#==============================================================
# Maintain mode
#==============================================================
# maintain : true
maintain : false


#==============================================================
# Administator info
#==============================================================
admin_name: KANGXI
admin_email: hello@example.com


#==============================================================
# Site settings
#==============================================================
site_name         : Bisous 喜帖產生器
site_title        : Bisous 喜帖產生器
site_description  : 網站描述
site_url          : https://bisous.com.tw
site_version      : 1.0.0
og_type           : website
og_image          : https://bisous.com.tw/images/fb.jpg
ga_track_id       : UA-XXXXXXXX-XX


#==============================================================
# Facebook APP
#==============================================================
fb_app_id: XXXXXXXXXXXXXXXX
fb_app_version: v2.5


#==============================================================
# Build exclude
#==============================================================
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - assets


#==============================================================
# Html compress config
#==============================================================
compress_html:
  clippings: all

